export const artworks = [
  {
    author: "Picasso / 피카소",
    title: "The Rainbow Dove (무지개비둘기)",
    price: "243,055.56 USDC",
    material: "Lithography",
    size: "53.5 x 65.4cm",
    year: "1952.10.23",
    edition: "199/250",
    image: "/art/01.webp",
    slide_number: 4,
    id: 1,
  },
  {
    author: "Picasso / 피카소",
    title: "Composition au Vase des Fleurs",
    price: "243,055.56 USDC",
    material: "Lithography",
    size: "51.8 x 64.2cm",
    year: "1947.3.10",
    edition: "199/250",
    image: "/art/02.webp",
    slide_number: 5,
    id: 2,
  },
  {
    author: "Picasso / 피카소",
    title: "L'atelier de Cannes (칸의작업실)",
    price: "243,055.56 USDC",
    material: "Lithography",
    size: "65.5 x 55.7cm",
    year: "1956.4.7",
    edition: "199/250",
    image: "/art/03.webp",
    slide_number: 6,
    id: 3,
  },
  {
    author: "Picasso / 피카소",
    title: "Galerie Jorgen, l'Atelier",
    price: "243,055.56 USDC",
    material: "Lithography",
    size: "63.7 x 51.8cm",
    year: "1947.2.16",
    edition: "199/250",
    image: "/art/04.webp",
    slide_number: 7,
    id: 4,
  },
  {
    author: "Picasso / 피카소",
    title: "Portraits Imaginaires Ⅰ",
    price: "1,736,111.11 USDC",
    material: "Lithography",
    size: "82.5 x 62.8cm",
    year: "1969.2.27",
    edition: "Marcel Salinas 제작",
    image: "/art/05.webp",
    slide_number: 8,
    id: 5,
  },
  {
    author: "Picasso / 피카소",
    title: "Portraits Imaginaires Ⅲ",
    price: "1,736,111.11 USDC",
    material: "Lithography",
    size: "82.5 x 62.8cm",
    year: "1969.3.12",
    edition: "Marcel Salinas 제작",
    image: "/art/06.webp",
    slide_number: 9,
    id: 6,
  },
  {
    author: "Picasso / 피카소",
    title: "Carnet de Californie",
    price: "208,333.33 USDC",
    material: "Lithography",
    size: "50.7 x 39cm",
    year: "1955.11.21",
    edition: "",
    image: "/art/07.webp",
    slide_number: 10,
    id: 7,
  },
  {
    author: "Picasso / 피카소",
    title: "PIERROT ET ARLEQUIN",
    price: "208,333.33 USDC",
    material: "Pochoir",
    size: "24.2 x 29.7cm",
    year: "1933",
    edition: "",
    image: "/art/08.webp",
    slide_number: 11,
    id: 8,
  },
  {
    author: "Picasso / 피카소",
    title: "Seated Woman with a Mandolin",
    price: "208,333.33 USDC",
    material: "Pochoir",
    size: "29.8 x 23.4cm",
    year: "1955.11.18",
    edition: "",
    image: "/art/09.webp",
    slide_number: 12,
    id: 9,
  },
  {
    author: "Picasso / 피카소",
    title: `"SILVANA" EDITORIALE D'ARTE"`,
    price: "39,191.31 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Book",
    image: "/art/010.webp",
    slide_number: 13,
    id: 10,
  },
  {
    author: "Picasso / 피카소",
    title: "LA COPPIA，I MISERABILI",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Firmato in basso a sinistra",
    image: "/art/011.webp",
    slide_number: 14,
    id: 11,
  },
  {
    author: "Picasso / 피카소",
    title: "SALTIMBANCO SEDUTO CON",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Firmato in basso a sinistra",
    image: "/art/012.webp",
    slide_number: 15,
    id: 12,
  },
  {
    author: "Picasso / 피카소",
    title: "TESTA，Studio per la Danza con i veli",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Firmato in basso a destra",
    image: "/art/013.webp",
    slide_number: 16,
    id: 13,
  },
  {
    author: "Picasso / 피카소",
    title: "DONNA, STUDIO PER LES",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Firma in alto a sinistra, molto",
    image: "/art/014.webp",
    slide_number: 17,
    id: 14,
  },
  {
    author: "Picasso / 피카소",
    title: "STUDIO PER LES",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Firmato in basso, al centro",
    image: "/art/015.webp",
    slide_number: 18,
    id: 15,
  },
  {
    author: "Picasso / 피카소",
    title: "MA JOLIE",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Firmato sul verso",
    image: "/art/016.webp",
    slide_number: 19,
    id: 16,
  },
  {
    author: "Picasso / 피카소",
    title: "LE JOURNAL",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Firmato e datato in basso a destra",
    image: "/art/017.webp",
    slide_number: 20,
    id: 17,
  },
  {
    author: "Picasso / 피카소",
    title: "COMPOSIZIONE CON PIPA",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Collezione Othmar Huber Glarus",
    image: "/art/018.webp",
    slide_number: 21,
    id: 18,
  },
  {
    author: "Picasso / 피카소",
    title: "CHITARRA, BOTTIGLIA E",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Datato in basso a destra: 10/4/21",
    image: "/art/019.webp",
    slide_number: 22,
    id: 19,
  },
  {
    author: "Picasso / 피카소",
    title: "ARLECCHINO CON LA",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Firmato e datato in alto a sinistra",
    image: "/art/020.webp",
    slide_number: 23,
    id: 20,
  },
  {
    author: "Picasso / 피카소",
    title: "FRUTTIERA E CHITARRA SU",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Sul verso: 11 Fevrier, fait entre 2 Hs",
    image: "/art/021.webp",
    slide_number: 24,
    id: 21,
  },
  {
    author: "Picasso / 피카소",
    title: "BAGNANTE CHE GIOCA AL",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Sul verso: Boisgeloup, 30 Août",
    image: "/art/022.webp",
    slide_number: 25,
    id: 22,
  },
  {
    author: "Picasso / 피카소",
    title: "DONNA NELLA POLTRONA",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Sul verso: Avril XXXII",
    image: "/art/023.webp",
    slide_number: 26,
    id: 23,
  },
  {
    author: "Picasso / 피카소",
    title: "DONNA SEDUTA",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Sul verso: 4/1/38",
    image: "/art/024.webp",
    slide_number: 27,
    id: 24,
  },
  {
    author: "Picasso / 피카소",
    title: "DONNA NUDA",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Datato in alto a sinistra -",
    image: "/art/025.webp",
    slide_number: 28,
    id: 25,
  },
  {
    author: "Picasso / 피카소",
    title: "GATTO CHE ADDENTA UN",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Datato in alto a sinistra 22/4/39",
    image: "/art/026.webp",
    slide_number: 29,
    id: 26,
  },
  {
    author: "Picasso / 피카소",
    title: "RAGAZZA SEDUTA",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Sul verso: 3/7/46",
    image: "/art/027.webp",
    slide_number: 30,
    id: 27,
  },
  {
    author: "Picasso / 피카소",
    title: "DONNA NUDA",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Sul verso: 19/2/49",
    image: "/art/028.webp",
    slide_number: 31,
    id: 28,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 31",
    price: "270,324.01 USDC",
    material: "Ink on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/029.webp",
    slide_number: 31,
    id: 29,
  },
  {
    author: "Picasso / 피카소",
    title: "MATERNITA' E ARANCIA",
    price: "173,611.11 USDC",
    material: "Pochoir",
    size: "39 x 28.5cm",
    year: "1955",
    edition: "Sul verso: 25/1/51 Vallauris",
    image: "/art/030.webp",
    slide_number: 32,
    id: 30,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 32",
    price: "49,191.31 USDC",
    material: "Charcoal sketch",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/031.webp",
    slide_number: 32,
    id: 31,
  },
  {
    author: "Picasso / 피카소",
    title: "SKETCHBOOK",
    price: "42,191.31 USDC",
    material: "Lithography",
    size: "43 x 27cm",
    year: "1959.11.3",
    edition: "1/1000",
    image: "/art/032.webp",
    slide_number: 33,
    id: 32,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 33",
    price: "301,640.73 USDC",
    material: "Charcoal sketch",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/033.webp",
    slide_number: 33,
    id: 33,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 34",
    price: "124,615.68 USDC",
    material: "Charcoal sketch",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/034.webp",
    slide_number: 34,
    id: 34,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 35",
    price: "210,00 USDC",
    material: "Oil on canvas",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/035.webp",
    slide_number: 35,
    id: 35,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 36",
    price: "106,249.19 USDC",
    material: "Ink on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/036.webp",
    slide_number: 36,
    id: 36,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 37",
    price: "248,470.59 USDC",
    material: "Ink on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/037.webp",
    slide_number: 37,
    id: 37,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 38",
    price: "225,590.61 USDC",
    material: "Lithography",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/038.webp",
    slide_number: 38,
    id: 38,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 39",
    price: "157,008.86 USDC",
    material: "Ink on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/039.webp",
    slide_number: 39,
    id: 39,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 40",
    price: "272,724.29 USDC",
    material: "Pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/040.webp",
    slide_number: 40,
    id: 40,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 41",
    price: "54,903.09 USDC",
    material: "Pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/041.webp",
    slide_number: 41,
    id: 41,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 42",
    price: "97,090.22 USDC",
    material: "Charcoal sketch",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/042.webp",
    slide_number: 42,
    id: 42,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 43",
    price: "307,354.43 USDC",
    material: "Pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/043.webp",
    slide_number: 43,
    id: 43,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 44",
    price: "172,326.25 USDC",
    material: "Charcoal sketch",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/044.webp",
    slide_number: 44,
    id: 44,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 45",
    price: "263,588.68 USDC",
    material: "Lithography",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/045.webp",
    slide_number: 45,
    id: 45,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 46",
    price: "225,843.22 USDC",
    material: "Lithography",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/046.webp",
    slide_number: 46,
    id: 46,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 47",
    price: "197,196.51 USDC",
    material: "Charcoal sketch",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/047.webp",
    slide_number: 47,
    id: 47,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 48",
    price: "245,093.89 USDC",
    material: "Ink on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/048.webp",
    slide_number: 48,
    id: 48,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 49",
    price: "137,587.12 USDC",
    material: "Pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/049.webp",
    slide_number: 49,
    id: 49,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 50",
    price: "287,885.78 USDC",
    material: "Pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/050.webp",
    slide_number: 50,
    id: 50,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 51",
    price: "34,990.30 USDC",
    material: "Color pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/051.webp",
    slide_number: 51,
    id: 51,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 52",
    price: "98,323.78 USDC",
    material: "Oil on canvas",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/052.webp",
    slide_number: 52,
    id: 52,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 53",
    price: "44,687.99 USDC",
    material: "Charcoal sketch",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/053.webp",
    slide_number: 53,
    id: 53,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 54",
    price: "40,547.86 USDC",
    material: "Ink on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/054.webp",
    slide_number: 54,
    id: 54,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 55",
    price: "204,212.91 USDC",
    material: "Lithography",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/055.webp",
    slide_number: 55,
    id: 55,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 56",
    price: "57,917.04 USDC",
    material: "Color pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/056.webp",
    slide_number: 56,
    id: 56,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 57",
    price: "251,744.17 USDC",
    material: "Ink on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/057.webp",
    slide_number: 57,
    id: 57,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "30,191.31 USDC",
    material: "Aquatint, Etching, Dry point",
    size: "제작연도",
    year: "1968.3.16 ~ 1968.10.8",
    edition: "",
    image: "/art/058.webp",
    slide_number: 58,
    id: 58,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 58",
    price: "144,273.77 USDC",
    material: "Color pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/059.webp",
    slide_number: 58,
    id: 59,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "41.5 x 31.5cm",
    year: "March 25,1968",
    edition: "",
    image: "/art/060.webp",
    slide_number: 59,
    id: 60,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 59",
    price: "130,127.56 USDC",
    material: "Lithography",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/061.webp",
    slide_number: 59,
    id: 61,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "42 x 31.5cm",
    year: "March 29,1968",
    edition: "",
    image: "/art/062.webp",
    slide_number: 60,
    id: 62,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 60",
    price: "194,661.14 USDC",
    material: "Ink on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/063.webp",
    slide_number: 60,
    id: 63,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "42 x 31.5cm",
    year: "March 29,1968",
    edition: "",
    image: "/art/064.webp",
    slide_number: 61,
    id: 64,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 61",
    price: "107,603.39 USDC",
    material: "Color pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/065.webp",
    slide_number: 61,
    id: 65,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "42 x 31.5cm",
    year: "March 30,1968",
    edition: "",
    image: "/art/066.webp",
    slide_number: 62,
    id: 66,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 62",
    price: "189,491.91 USDC",
    material: "Color pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/067.webp",
    slide_number: 62,
    id: 67,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "41.5 x 31.5cm",
    year: "March 30,1968",
    edition: "",
    image: "/art/068.webp",
    slide_number: 63,
    id: 68,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 63",
    price: "66,560.43 USDC",
    material: "Mixed media on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/069.webp",
    slide_number: 63,
    id: 69,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "31.5 x 42cm",
    year: "April 3,1968",
    edition: "",
    image: "/art/070.webp",
    slide_number: 64,
    id: 70,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 64",
    price: "272,794.37 USDC",
    material: "Color pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/071.webp",
    slide_number: 64,
    id: 71,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "37.5 x 27.5cm",
    year: "April 6,1968",
    edition: "",
    image: "/art/072.webp",
    slide_number: 65,
    id: 72,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 65",
    price: "258,618.20 USDC",
    material: "Charcoal sketch",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/073.webp",
    slide_number: 65,
    id: 73,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint, Etching",
    size: "37.5 x 27.5cm",
    year: "April 6,1968",
    edition: "",
    image: "/art/074.webp",
    slide_number: 66,
    id: 74,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 66",
    price: "212,650.11 USDC",
    material: "Color pencil on paper",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/075.webp",
    slide_number: 66,
    id: 75,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint",
    size: "32 x 47cm",
    year: "April 8,1968",
    edition: "",
    image: "/art/076.webp",
    slide_number: 67,
    id: 76,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 67",
    price: "291,362.63 USDC",
    material: "Lithography",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/077.webp",
    slide_number: 67,
    id: 77,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "31.5 x 41.5cm",
    year: "April 8,1968",
    edition: "",
    image: "/art/078.webp",
    slide_number: 68,
    id: 78,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 68",
    price: "266,777.50 USDC",
    material: "Charcoal sketch",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/079.webp",
    slide_number: 68,
    id: 79,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "31.5 x 41.5cm",
    year: "April 8,1968",
    edition: "",
    image: "/art/080.webp",
    slide_number: 69,
    id: 80,
  },
  {
    author: "Picasso / 피카소",
    title: "Untitled Sketch 69",
    price: "69,893.61 USDC",
    material: "Lithography",
    size: "Unknown",
    year: "1955-11",
    edition: "N/A",
    image: "/art/081.webp",
    slide_number: 69,
    id: 81,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "31.5 x 41.5cm",
    year: "April 11,1968",
    edition: "",
    image: "/art/082.webp",
    slide_number: 70,
    id: 82,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "10,416.67 USDC",
    material: "Etching",
    size: "6 x 12cm",
    year: "April 11,1968",
    edition: "",
    image: "/art/083.webp",
    slide_number: 71,
    id: 83,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "10,416.67 USDC",
    material: "Etching",
    size: "12.5 x 6cm",
    year: "April 11,1968",
    edition: "",
    image: "/art/084.webp",
    slide_number: 72,
    id: 84,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "31.5 x 41.5cm",
    year: "April 11,1968",
    edition: "",
    image: "/art/085.webp",
    slide_number: 73,
    id: 85,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "31.5 x 41.5cm",
    year: "April 11,1968",
    edition: "",
    image: "/art/086.webp",
    slide_number: 74,
    id: 86,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint, Etching and",
    size: "32 x 47cm",
    year: "April 12,1968",
    edition: "",
    image: "/art/087.webp",
    slide_number: 75,
    id: 87,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "31.5 x 41.5cm",
    year: "April 12,1968",
    edition: "",
    image: "/art/088.webp",
    slide_number: 76,
    id: 88,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint, Etching",
    size: "31.5 x 39.5cm",
    year: "April 13,1968",
    edition: "",
    image: "/art/089.webp",
    slide_number: 77,
    id: 89,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint",
    size: "31.5 x 39.5cm",
    year: "April 14,1968",
    edition: "",
    image: "/art/090.webp",
    slide_number: 78,
    id: 90,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint, Dry point",
    size: "31.5 x 39.5cm",
    year: "April 14,1968",
    edition: "",
    image: "/art/091.webp",
    slide_number: 79,
    id: 91,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint, Etching",
    size: "27.5 x 38.5cm",
    year: "April 15,1968",
    edition: "",
    image: "/art/092.webp",
    slide_number: 80,
    id: 92,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint, Etching and Dry point",
    size: "22.5 x 32cm",
    year: "April 15, 17-19, 1968",
    edition: "",
    image: "/art/093.webp",
    slide_number: 81,
    id: 93,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "31.5 x 39.5cm",
    year: "April 20,1968",
    edition: "",
    image: "/art/094.webp",
    slide_number: 82,
    id: 94,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint, Dry point",
    size: "31.5 x 39.5cm",
    year: "April 20,1968",
    edition: "",
    image: "/art/095.webp",
    slide_number: 83,
    id: 95,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint, Dry point",
    size: "31.5 x 39.5cm",
    year: "April 21,22,1968",
    edition: "",
    image: "/art/096.webp",
    slide_number: 84,
    id: 96,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "28 x 39cm",
    year: "April 21, 1968",
    edition: "",
    image: "/art/097.webp",
    slide_number: 85,
    id: 97,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "28 x 39cm",
    year: "April 22, 1968",
    edition: "",
    image: "/art/098.webp",
    slide_number: 86,
    id: 98,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint, Etching and Dry point",
    size: "31.5 x 39.5cm",
    year: "April 23,1968",
    edition: "",
    image: "/art/099.webp",
    slide_number: 87,
    id: 99,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "10,416.67 USDC",
    material: "Aquatint",
    size: "12.5 x 9cm",
    year: "April 24,1968",
    edition: "",
    image: "/art/0100.webp",
    slide_number: 88,
    id: 100,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "10,416.67 USDC",
    material: "Aquatint",
    size: "12.5 x 9cm",
    year: "April 24,1968",
    edition: "",
    image: "/art/0101.webp",
    slide_number: 89,
    id: 101,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint, Etching and Dry point",
    size: "31.5 x 39.5cm",
    year: "April 24,1968",
    edition: "",
    image: "/art/0102.webp",
    slide_number: 90,
    id: 102,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "28 x 39cm",
    year: "April 26,1968",
    edition: "",
    image: "/art/0103.webp",
    slide_number: 91,
    id: 103,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Aquatint, Etching",
    size: "28 x 39cm",
    year: "April 29,1968",
    edition: "",
    image: "/art/0104.webp",
    slide_number: 92,
    id: 104,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "31.5 x 39.5cm",
    year: "April 29,1968",
    edition: "",
    image: "/art/0105.webp",
    slide_number: 93,
    id: 105,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "15.5 x 20.5cm",
    year: "April 18,1968",
    edition: "",
    image: "/art/0106.webp",
    slide_number: 94,
    id: 106,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "20 x 32.5cm",
    year: "April 18,1968",
    edition: "",
    image: "/art/0107.webp",
    slide_number: 95,
    id: 107,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "15.5 x 20.5cm",
    year: "April 18,1968",
    edition: "",
    image: "/art/0108.webp",
    slide_number: 96,
    id: 108,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "15.5 x 20.5cm",
    year: "April 18,1968",
    edition: "",
    image: "/art/0109.webp",
    slide_number: 97,
    id: 109,
  },
  {
    author: "Picasso / 피카소",
    title: "347 Series",
    price: "20,833.33 USDC",
    material: "Etching",
    size: "28 x 39cm",
    year: "April 20,1968",
    edition: "",
    image: "/art/0110.webp",
    slide_number: 98,
    id: 110,
  },
];
